### ISSUE TITLE
How about using "from janim import" instead?

### ISSUE THREAD

**Issue by Samuelhzx** [jkjkil4/JAnim#1]
by adding imports in `__init__.py`, we can use `from janim import *` instead of  `from janim.imports import *`. We can move the code in `imports.py` into `__init__.py`, or simply add `from janim.imports import *` to `__init__.py`, like this:
![](https://github.com/jkjkil4/JAnim/assets/115335868/e91a852a-d453-4e9a-be7b-cdecbb8b0a65)
and it works:
![it works](https://github.com/jkjkil4/JAnim/assets/115335868/3226daa5-16cc-469d-bf30-0f361c3f89b6)
——manim群友Samuelhzx

**Comment by jkjkil4** [comment]
If you just want to import a part of janim, put imports into `__init__.py` could result in a huge overhead, so I put them into `imports.py` instead.
