### ISSUE TITLE
【文档BUG】fading 文档页面 FadeIn 示例代码放错了

### ISSUE THREAD

**Issue by victcity** [jkjkil4/JAnim#7]
我猜应该是翻译的时候放错位置了
https://janim.readthedocs.io/zh-cn/latest/janim/anims/fading.html
两个示例都是 class FadeOutExample
![chrome_l8POfQiLQ2](https://github.com/jkjkil4/JAnim/assets/11360094/424f7357-fdb8-49d8-9eec-262e009d8364)
![chrome_WD2CPAk5SL](https://github.com/jkjkil4/JAnim/assets/11360094/6d2b39f5-c3b7-4bf8-98e9-8557cb9cad12)

**Comment by jkjkil4** [comment]
改好了，一会我重新构建一下
